apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/kubeflow/manifests/profiles/base_v3?ref=v1.2-branch
configMapGenerator:
  # We need the name to be unique without the suffix because the original name is what
  # gets used with patches
  - name: profiles-config
    literals:
      - admin=gg